[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pylint.messages_control]
disable = "missing-module-docstring, too-few-public-methods"

[tool.pylint.format]
max-line-length = "88"

[tool.black]
line-length = 88
target-version = ['py39']
